name = "remix-cloudflare-workers"
type = "webpack"

zone_id = ""
account_id = ""
route = ""
workers_dev = true
webpack_config = "webpack.config.js"

kv_namespaces = [{ binding = "MY_KV", id = "3679ef366be04cb7bb5b224ec8b625ac" }]

[site]
bucket = "./public"
entry-point = "."

[build]
watch_dir = "build/index.js"

[build.upload]
format="service-worker"
